version: "3.8"
services:
  nginx:
    image: nginx:alpine
    container_name: nginx_cont
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - admin
      - backend
    networks:
      - foodnet

  mongo:
    image: mongo:7
    container_name: mongo_cont
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "27017"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - foodnet

  backend:
    build: ./backend
    container_name: backend_cont
    restart: always
    expose:
      - "4000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - foodnet

  frontend:
    build: ./frontend
    container_name: frontend_cont
    expose:
    - "80"
    restart: always
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/index.html"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - foodnet

  admin:
    build: ./admin
    container_name: admin_cont
    expose:
    - "80"
    restart: always
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/index.html"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - foodnet

volumes:
  mongo_data:
    driver: local

networks:
  foodnet:
    driver: bridge
